### ISSUE TITLE
Sonarqube 25_12 support

### ISSUE THREAD

**Issue by JulienVermelinDG** [green-code-initiative/creedengo-javascript#98]
### Current Behavior

Is a version compatible with SonarQube 25_12 planned? 
Currently, when I try to install SonarQube with this plugin, I get this error on start :
java.lang.NoClassDefFoundError:org/sonar/plugins/javascript/api/EslintBasedCheck.

If I disable the plugin, the installation is successful (Sonarqube is started).

### Expected Behavior

Successful installation with the plugin.

### Steps to Reproduce

Install Sonarqube 25_12 with the plugin.

### Failure Logs

```shell
java.lang.NoClassDefFoundError:org/sonar/plugins/javascript/api/EslintBasedCheck
```

### creedengo-javascript Version

2.1.0

### SonarQube Version

25.12.0.117093

**Comment by utarwyn** [comment]
Hello! Thank you for the report 💯 

Indeed, SonarQube introduced breaking changes to their API in recent versions. We will need to work on a new major version of the plugin that only works with these newer versions. Probably in two steps: **a final v2.x.x** for SonarQube up to 25.10 and a **v3.0.0** for this new support.

**Comment by utarwyn** [comment]
Hello! I would like to keep you informed of progress on this issue.

- I released [version 2.2.0](https://github.com/green-code-initiative/creedengo-javascript/releases/tag/2.2.0) of the plugin last week with the latest developments. It is supported up to SonarQube Community **25.8** and SonarQube Developer **2025.4 LTA**.
  👉 This will be the last one; there will be **no more 2.x versions** of the plugin.

- I have started to work on Creedengo JavaScript **v3.0.0** which will upgrade the plugin's prerequisites and support the latest APIs offered by SonarQube.
  👉 **BUT** I'm having trouble defining these new prerequisites, because this new API doesn't seem to support the latest LTA (2025.4). So I've asked the team that manages SonarJS [here](https://github.com/green-code-initiative/creedengo-javascript/discussions/96) for some information. I hope to hear back very soon.


I will get back to you as soon as I have any news.

**Comment by utarwyn** [comment]
Hi @tdaskalovaxway 👋 

Good news: work on v3.0.0 is actively in progress on the [move-to-v3 branch](https://github.com/green-code-initiative/creedengo-javascript/tree/move-to-v3). The migration to the new SonarJS API is complete, and the plugin now requires:

- SonarQube Server 2025.4.x LTA
- SonarQube Community 25.6 - 25.11
- Java 17
- ESLint 9+ / Node 22+

The implementation is done and I am doing some tests with different versions of SonarQube based on feedbacks I got in [discussion #96](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) regarding LTA support compatibility. We should be able to release it in the next few days! 🚀

**Comment by utarwyn** [comment]
Hello! I am pleased to announce that **Creedengo JS v3** is live 🚀 
Check the full detail in the release : https://github.com/green-code-initiative/creedengo-javascript/releases/tag/3.0.0

I will publish this version asap on SonarQube marketplace!
Open a new ticket if needed 👀
